# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.8.0.4
    hooks:
      # Run shellcheck for all .sh files
      - id: shellcheck

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      # Format Python files
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Clean up trailing whitespace
      - id: trailing-whitespace

      # Ensure files have a proper EOL
      - id: end-of-file-fixer

      # All non-bat files should end with LF
      - id: mixed-line-ending
        name: Ensure LF endings on most files
        args: ["--fix=lf"]
        exclude: \.bat$

      # Bat files should be CRLF ending
      - id: mixed-line-ending
        name: Ensure CFLF endings on Windows files
        args: ["--fix=crlf"]
        files: \.bat$

      # Check for files that contain merge conflict strings
      - id: check-merge-conflict

      # Check for debugger imports and py37+ `breakpoint()` calls in python source
      - id: debug-statements

      # Check yaml files for parseable syntax
      - id: check-yaml

      # Prevent giant files from being committed
      - id: check-added-large-files

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      # Do a security scan with Bandit
      - id: bandit
        args: ["--ini", ".bandit", "-r"]
        exclude: |
          (?x)^(
            .*/tests/.*
          )$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      # Run prettier to format non-Python files
      - id: prettier

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/twu/skjold
    rev: v0.6.0
    hooks:
      - id: skjold
